### PR TITLE
Java Client documentation

### PR DESCRIPTION
**Pull request by dcrissman**
This is only a start.

Let me know what you think.

### CODE REVIEW

**Comment by bserdar** [comment]
+ValueQuery.withValue("enumField $in [success, partial]"); 

Is this correct? No quotes around string literals?

**Comment by bserdar** [comment]
"You can use the wildcard character '*' in place of the fieldName to indicate all fields"

If this uses the same semantics as lightblue query language:
- '*' means all root-level fields
- x.\* means all fields under x, or all array elements of x.

**Comment by luan-cestari** [comment]
Moved to in_progress as Burak made some comments

**Comment by dcrissman** [comment]
Closing as a refactor has invalidated this documentation. See #33 to redo this in the future.

**Pull request closed without merging**
